// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmCnnmLj6LoI2j-nObRBTlM8hg-EH8JOQ',
    appId: '1:584804574600:web:c8cd8f4f1bbb12e65b863d',
    messagingSenderId: '584804574600',
    projectId: 'ai-quant-eaf3d',
    authDomain: 'ai-quant-eaf3d.firebaseapp.com',
    storageBucket: 'ai-quant-eaf3d.appspot.com',
    measurementId: 'G-71X41DG1H2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDW0lgI8eOc6nwbwDCJ0xETtq3bfRr8FU',
    appId: '1:584804574600:android:1663e565b0a5dc045b863d',
    messagingSenderId: '584804574600',
    projectId: 'ai-quant-eaf3d',
    storageBucket: 'ai-quant-eaf3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz_c5_MoOKQHGJDZoK28WGiPga5H6pabI',
    appId: '1:584804574600:ios:40483c26f4be68e05b863d',
    messagingSenderId: '584804574600',
    projectId: 'ai-quant-eaf3d',
    storageBucket: 'ai-quant-eaf3d.appspot.com',
    iosClientId: '584804574600-533rba1nf0ikn3r7c9egoq4hm8j4ebek.apps.googleusercontent.com',
    iosBundleId: 'com.aiquant.aiQuant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz_c5_MoOKQHGJDZoK28WGiPga5H6pabI',
    appId: '1:584804574600:ios:baabbacac1191de95b863d',
    messagingSenderId: '584804574600',
    projectId: 'ai-quant-eaf3d',
    storageBucket: 'ai-quant-eaf3d.appspot.com',
    iosClientId: '584804574600-p5d3cfeaa06t3u1vq25tkmfd14r1cg1v.apps.googleusercontent.com',
    iosBundleId: 'com.aiquant.aiQuant.RunnerTests',
  );
}
